### ISSUE TITLE
Return Code Invalid

### ISSUE THREAD

**Issue by mateusrmos** [checkdomain/TeleCash#1]
In Brazil, the Node ProcessorResponseMessage has been translated to the local language(PT-BR), this way is not trustfull anymore, and the correction is the following.

TeleCash/lib/Checkdomain/TeleCash/IPG/API/Response/Order/Sell.php

    const RESPONSE_SUCCESS_NEW = 'APPROVED';
    private function checkIfSuccessful(\DOMDocument $responseDoc)
    {
        $this->wasSuccessful = false;

        $list = $responseDoc->getElementsByTagNameNS(OrderService::NAMESPACE_N3, 'successfully');
        if ($list->length > 0) {
            $success = $responseDoc->getElementsByTagNameNS(OrderService::NAMESPACE_N3, 'successfully')->item(0)->nodeValue;

            $this->wasSuccessful = ($success === 'true');
        } else {
            $list = $responseDoc->getElementsByTagNameNS(OrderService::NAMESPACE_N3, 'ProcessorResponseMessage');
            if ($list->length > 0) {
                $this->wasSuccessful = ($list->item(0)->nodeValue === Sell::RESPONSE_SUCCESS);
            }
            if($this->wasSuccessful == false){
                $list = $responseDoc->getElementsByTagNameNS(OrderService::NAMESPACE_N3, 'TransactionResult');
                if ($list->length > 0) {
                    $this->wasSuccessful = ($list->item(0)->nodeValue === Sell::RESPONSE_SUCCESS_NEW);
                }
            }
        }
        return $this->wasSuccessful;
    }

**Comment by TPete** [comment]
Hi @mateusramos,

I have added the fallback to checking the `TransactionResult`, as you have suggested. Hope this helps with your issue.
